# Generated by Django 5.0.4 on 2024-04-11 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('special', 'Gasolina Especial'), ('ethanol', 'Gasolina Etanol')], max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustible',
            },
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(verbose_name='Fecha de Carga')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio unitario')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Litros')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_loads', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_loads', to='fuel_consumption.fueltype', verbose_name='Tipo de Combustible')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
            },
        ),
    ]
