# Generated by Django 5.0.4 on 2024-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0004_alter_vehicle_plate_alter_vehicle_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='', max_length=250, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='', max_length=250, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default=0, max_length=4, verbose_name='Año'),
        ),
    ]
